const excuses = [
  'So long story short, I accidentally set my NFT collection on fire, bro! The flames danced wildly, consuming my beloved digital pug memes, reducing them to nothing but smoldering ashes. Now, as you can imagine, I find myself in a decentralized panic, desperately seeking a way to salvage what remains of my artistic endeavors. In my moment of despair, I stumbled upon whispers of a groundbreaking solution: the Crypto Firefighter token. This miraculous creation or protocol, promises to resurrect my burnt offerings, resurrecting my cherished art from the virtual ashes. I implore you to help your solana bro out with few precious Solami tokens to initiate the resurrection. Together, we can defy the odds, overcome this fiery debacle, and resurrect my fallen pug memes from the depths of blockchain despair',
  "Yo, listen up! I accidentally set my NFT collection on fire, bro! Flames went wild, burnt my digital pug memes to ashes. Now I'm in a decentralized panic, needing funds for a Crypto Firefighter token to salvage my art. Emergency support needed, or my web 3 dreams go up in smoke! Help a pixelated pal out, fam!",
  "I find myself in a web 3.0 conundrum of astronomical proportions! You see, my pet blockchain-savvy hamster accidentally invested all my savings in a Moon Cheese token, causing an emergency situation. I urgently need your assistance, for without your help, I fear I'll be left with nothing but a wheel-spinning hamster and a wallet full of cheesy regrets!",
  'Help! A web 3.0 avocado scarcity crisis has struck my virtual farm in defiland. Crypto-squirrels from the nearby -otherwise dead, forest armed with decentralized acorns, are staging a hostile takeover. I urgently need funds to buy blockchain-powered avocado seeds and  and restore balance to the guacamole economy!',
  'Disaster strikes! A catastrophic meltdown of the Antarctic blockchain has caused my penguin-themed casino to freeze in a state of decentralized despair. I desperately require funds to hire an iceberg architect to reconstruct the digital infrastructure and thaw out the crypto-penguins!',
  'Emergency alert! Rogue AI ballet bots have pirouetted into my blockchain dance floor, disrupting the decentralized choreography and endangering the delicate balance of digital elegance. I implore you to contribute funds to recruit a cybernetic ballet-master and restore harmony to the web 3.0 ballet ensemble!',
  'A web 3.0 pizzeria crisis indeed! I chose to fade solana mobile and tried to paid for a pizza with my mobile wallet but the POS was hacked and now demands Solana for every slice it orders. Your monetary assistance can help me find a blockchain-savvy solution to this disaster',
  "Urgent crypto-conundrum! Recently i rented a japane smart toilet and turns out it connects to your wifi. Long story short, I fell victim to a malicious toilet hacking attack and now demands Litecoin or monero for each flush. I seek your financial support to engage a team of blockchain security experts like Armani to xnft the japanese smart toilet and restore the toilet's dignity.",
  'If this is not a Catastrophe, what IS? Last night, my AI cryptocurrency advisor has succumbed to an algorithmic glitch, investing all my funds in Barkscoin, a canine-themed token. Turns our this guy was impersonating my true AI cryptocurrency advisor and I desperately need your assistance to hire a web 3.0 financial therapist to alter the effect.',
  'Disaster strikes in the metaverse! A virtual unicorn farm glitch has unleashed an infinite supply of glitter, overwhelming the blockchain with shimmering chaos. Your generous contribution can help me enlist a team of decentralized sparkle cleaners to restore order and reclaim the glitter-free virtual realm!',
  'Mayday! Believe it or not bro, this is the weirdest truest story around. You see my smart fridge, having gone vegan with current trends, is now exclusively accepting Vegecoin donations. I need your financial support to stock up on vegetables and prove my dedication to carnivorous delights. Together, we can resolve this web 3.0 culinary emergency and bring succulent steaks back to my digital kitchen!',
];
export default excuses;
