const coolness = [
  "You're like the secret sauce of the community, always adding that extra flavor",
  "You're a visionary thinker, always pushing the boundaries of what's possible",
  'You shine like a beacon of inspiration, illuminating the path for others to follow',
  'Your presence radiates greatness, making others strive to reach your level of achievement',
  "You're a true maestro in your field, your skill and dedication unmatched by anyone else",
  'Your brilliance is like a guiding star, leading us towards success and innovation',
  "You're the embodiment of success, a role model for aspiring professionals",
  'Your impact on the community is undeniable, you leave an indelible mark wherever you go',
  "You're a true trailblazer, paving the way for others with your unique perspective",
  "Your contributions are invaluable, making you an integral part of our community's success",
  "You're a true visionary, always pushing boundaries and exploring new frontiers",
  'Your talent is a force to be reckoned with, elevating the entire community',
  "You're a true master of your craft, captivating audiences with your expertise",
  'Your dedication to excellence is inspiring, making others strive for greatness',
  "You're an extraordinary talent, your work speaks volumes about your skill and passion",
  'Your impact on the community is profound, your influence spreads far and wide',
  "You're a true luminary, your expertise and knowledge make you a respected figure",
  'Your achievements are awe-inspiring, setting you apart as one of the best',
  "You're a pillar of strength in our community, providing guidance and support to others",
  'Your talent is like a beacon of inspiration, guiding others towards their own success',
  'You possess a unique brilliance that captivates everyone around you',
  'Your contributions have a transformative effect, shaping the community in profound ways',
  "You're a true innovator, always at the forefront of new trends and ideas",
  'Your expertise is unparalleled, making you a sought-after resource in the community',
  "You're a true role model, inspiring others to pursue their passions and dreams",
  'Your influence is far-reaching, leaving a lasting impact on the community',
  "You're a catalyst for growth and progress, propelling the community forward",
  'Your dedication and hard work are second to none, making you a standout among your peers',
  'You possess a remarkable talent that sets you apart from the rest',
  'Your commitment to excellence is unmatched, making you a true leader in the community',
  "You're a true icon in our community, your achievements speak for themselves",
  'Your passion is contagious, igniting a fire in others to pursue their own dreams',
  "You're a visionary thinker, always pushing the boundaries of what's possible",
  'Your contributions have a profound impact, shaping the community for the better',
  "You're a true maverick, carving your own path and inspiring others to do the same",
  'Your expertise is a valuable asset, earning you respect and admiration from all',
  'You possess an innate ability to inspire and motivate others with your work',
  'Your talent and dedication make you a standout figure in our community',
  "You're a true luminary, your brilliance shines through in everything you do",
];

export default coolness;
